// Code generated by logcopter-gen; DO NOT EDIT.

package registry

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("go-go-golems.devmesh.internal.registry")
